= Circuit Breaker - Node.js Example Application

IMPORTANT: This runs best when deployed to OpenShift in order to use the circuit breaker functionality. For more details on using this example application with a single-node OpenShift cluster, CI/CD deployments, as well as the rest of the runtime, see the link:https://access.redhat.com/documentation/en-us/red_hat_build_of_node.js/[Node.js Runtime Guide].

IMPORTANT: This example application requires Node.js 8.x or greater and `npm` 5 or greater.

IMPORTANT: As part of the process of creating this example application using developers.redhat.com/launch or the Fabric8 Launcher tool, set up a project with a CI/CD deployment of this example application. You can see the status of this deployment in your Single-node OpenShift Cluster or OpenShift Online Web Console.

== Running the Example Application on a Single-node OpenShift Cluster
If you have a single-node OpenShift cluster, such as Minishift or Red Hat Container Development Kit, installed and running, you can also deploy your example application there. A single-node OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

To deploy your example application to a running single-node OpenShift cluster:

. Log in and create your project.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ git clone git@github.com:maverickjoe123/observant-chicken

$ cd observant-chicken

$ oc login -u developer -p developer

$ oc new-project MY_PROJECT_NAME

$ ./start-openshift.sh
----

== Interacting with the Example Application on a Single-node OpenShift Cluster

To interact with your example application while it is running on a Single-node OpenShift Cluster, you first need to obtain its URL:

[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get route nodejs-cb-greeting -o jsonpath={$.spec.host}

nodejs-cb-greeting-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME

$ oc get route nodejs-cb-name -o jsonpath={$.spec.host}

nodejs-cb-name-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME
----


You can use the form at your application's URL or you can use the `curl` command:


[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://nodejs-cb-greeting-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME/api/greeting
{"content":"Hello, World!"}

$ curl -X PUT -H "Content-Type: application/json" -d '{"state": "fail"}' http://nodejs-cb-name-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME/api/state

$ curl http://nodejs-cb-greeting-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME/api/greeting
{"content":"Hello, Fallback!"}

$ curl -X PUT -H "Content-Type: application/json" -d '{"state": "ok"}' http://nodejs-cb-name-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME/api/state

$ curl http://nodejs-cb-greeting-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME/api/greeting
{"content":"Hello, World!"}
----

== More Information
You can learn more about this example application and the Node.js runtime in the link:https://access.redhat.com/documentation/en-us/red_hat_build_of_node.js/[Node.js Runtime Guide].


